/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
 * Generated on: 04-Dec-2023 02:58:09
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018b\extern\include\tmwtypes.h 
 */
const int BL = 11;
const real64_T B[11] = {
   0.007149677748699,-0.004816699287899, -0.03078125923432,  0.05388526087528,
    0.02786515810573,    0.893395723585,  0.02786515810573,  0.05388526087528,
   -0.03078125923432,-0.004816699287899, 0.007149677748699
};
